### PR TITLE
fix the api error

### PR DESCRIPTION
**Pull request by iyuq**
fix the api error, it should pass a null object to the callback as the first arguments

### CODE REVIEW

**Comment by whitlockjc** [comment]
This is not the appropriate way to go about fixing this.  `docs/API.md` is generated from the sources so you'd want to update the appropriate source to fix this.  Then you'd run `gulp` to lint check the code, test your changes and generate the binaries/documentation.  Update your PR appropriately and we'll get it merged.

**Comment by iyuq** [comment]
@whitlockjc  I changed this by change the comments in the code, is this okay?

**Comment by whitlockjc** [comment]
That's right but I would expect the generated files in `browser/*` to be updated as well.  Changing `index.js` was the right place to fix it so run `gulp`, add all files to the commit _(including the `browser/*.js` files)_ and update the PR.  Also, do you mind squashing your commits into one commit?

**Comment by iyuq** [comment]
@whitlockjc  It doesn't matter to squashing my commits into one. Is this all right?

**Comment by whitlockjc** [comment]
I would rather you squash the commits because it makes for an easier to understand Git history.  As for the current changes, they are accurate.

**Comment by iyuq** [comment]
@whitlockjc  I squash the commits into one in 4bbfcb52e5e7cb77ab86b570aa9492546420f3a0.

**Comment by iyuq** [comment]
@whitlockjc  I reopened a pull request to report the pull request

**Pull request closed without merging**
