### PR TITLE
Linting

### PR DESCRIPTION
**Pull request by brettz9**
- Linting (ESLint): Add `browser` to ignore, add `es6: true` (so `Promise` not seen as an undefined global)

### CODE REVIEW

**Comment by whitlockjc** [comment]
The same applies here that does to `json-refs` _(https://github.com/whitlockjc/json-refs/pull/134)_

**Comment by brettz9** [comment]
As with the other issue, I've updated the PR to include the requested `.eslintignore` changes and also simplified the gulp call (though here too, I'm not sure whether `.tern-project` should be included too?).

However, FWIW, your gulp script (before or after my simplification) errs out for me.

```
$ npm test

> path-loader@1.0.4 test /Users/brett/path-loader
> gulp

[07:13:33] Using gulpfile ~/path-loader/gulpfile.js
[07:13:33] Starting 'lint'...
[07:13:34] Starting 'nsp'...
[07:13:37] Starting 'browserify'...
[07:13:37] Starting 'test'...
[07:13:37] Starting 'pre-test'...
[07:13:38] Starting 'docs'...
(node:83424) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

events.js:136
      throw er; // Unhandled 'error' event
      ^
Error: There are no input files to process.
```

**Comment by brettz9** [comment]
Oh, and while the `gulp test` works without erring out, 3 tests fail:

```
  1) path-loader (node.js general) #load options.processContent error handling thrown error:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  

  2) path-loader (node.js general) #load options.processContent error handling returned error:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  

  3) path-loader (node.js loaders) #load https make sure we get a loader:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

**Comment by brettz9** [comment]
FWIW, I've rebased this onto `master`...

**Comment by whitlockjc** [comment]
I'm not sure these changes make sense.  This project doesn't use ES6 and the `Promise` global is provided by a library.  When getting these errors/warnings?  We already lint _(`eslint`)_ the sources.

**Pull request merged**
